export type DomainId =
  | 'cognitive-intelligence'
  | 'business-intelligence'
  | 'problem-solving'
  | 'communication'
  | 'leadership'
  | 'digital-business'
  | 'workspace-psychology';

export interface Domain {
  id: DomainId;
  number: string;
  name: string;
  description: string;
  assessmentType: string;
  totalQuestions: number;
  skills: string[];
  /** Whether this domain has a pass/fail outcome instead of a scored PRI */
  passFail: boolean;
  color: string; // Tailwind color class prefix for UI
}

export const DOMAINS: Domain[] = [
  {
    id: 'cognitive-intelligence',
    number: '1',
    name: 'Cognitive Intelligence',
    description: 'How you reason, analyse data, and think under time pressure',
    assessmentType: 'Adaptive MCQ',
    totalQuestions: 21,
    skills: [
      'Logical Reasoning - Syllogisms',
      'Logical Reasoning - Deductive chains',
      'Logical Reasoning - Arrangement and sequencing',
      'Logical Reasoning - Statement-conclusion relationships',
      'Logical Reasoning - Facts, assumptions, inferences',
      'Numerical Reasoning - Percentage change',
      'Numerical Reasoning - Ratio and proportion',
      'Numerical Reasoning - CAGR',
      'Numerical Reasoning - Work-rate problems',
      'Numerical Reasoning - Compound interest',
      'Data Interpretation - Bar charts and line charts',
      'Data Interpretation - Pie charts',
      'Data Interpretation - Data tables',
      'Data Interpretation - Trend identification',
      'Data Interpretation - Multi-source data integration',
      'Critical Thinking - Unstated assumptions',
      'Critical Thinking - Evidence strength',
      'Critical Thinking - Argument fallacies',
      'Critical Thinking - Strengthen and weaken arguments',
      'Critical Thinking - Correlation vs causation',
      'Pattern Recognition - Number series',
      'Pattern Recognition - Matrix and visual patterns',
      'Pattern Recognition - Alphanumeric sequences',
      'Pattern Recognition - Odd-one-out',
    ],
    passFail: false,
    color: 'blue',
  },
  {
    id: 'business-intelligence',
    number: '2',
    name: 'Business Intelligence',
    description: 'How well you read, interpret and act on business data and case information',
    assessmentType: 'Case-based MCQ',
    totalQuestions: 20,
    skills: [
      'Financial Statement Interpretation - Profit and loss statement',
      'Financial Statement Interpretation - Balance sheet',
      'Financial Statement Interpretation - Return ratios - ROE, ROA, ROCE',
      'Financial Statement Interpretation - Financial health indicators and red flags',
      'Financial Statement Interpretation - Working capital analysis',
      "Market Analysis - Porter's Five Forces",
      'Market Analysis - TAM, SAM, SOM',
      'Market Analysis - Market share',
      'Market Analysis - Market entry attractiveness',
      'Market Analysis - Market growth rate interpretation',
      'Unit Economics and Revenue Models - LTV and CAC',
      'Unit Economics and Revenue Models - Subscription metrics - MRR, ARR, churn',
      'Unit Economics and Revenue Models - Breakeven analysis',
      'Unit Economics and Revenue Models - SaaS and marketplace unit economics',
      'Unit Economics and Revenue Models - Pricing model implications',
      'Competitive Analysis and Business Models - Business model types',
      'Competitive Analysis and Business Models - Value chain analysis',
      'Competitive Analysis and Business Models - Generic competitive strategies',
      'Competitive Analysis and Business Models - Reading strategic position',
      'Competitive Analysis and Business Models - Competitive moats',
    ],
    passFail: false,
    color: 'emerald',
  },
  {
    id: 'problem-solving',
    number: '3',
    name: 'Problem Solving',
    description: 'How you break down complex business problems and build structured solutions',
    assessmentType: 'Case Simulation + MCQ',
    totalQuestions: 26,
    skills: [
      'MECE Decomposition - MECE principle',
      'MECE Decomposition - First-level problem splits',
      'MECE Decomposition - Issue trees',
      'MECE Decomposition - Hypothesis trees',
      'MECE Decomposition - Identifying MECE failures',
      'Root Cause Analysis - 5-Whys methodology',
      'Root Cause Analysis - Proximate cause vs root cause',
      'Root Cause Analysis - Causal variable isolation',
      'Root Cause Analysis - Operational data reading',
      'Root Cause Analysis - Systematic hypothesis elimination',
      'Hypothesis-Driven Thinking - Forming a prioritized hypothesis',
      'Hypothesis-Driven Thinking - Identifying confirming or denying data',
      'Hypothesis-Driven Thinking - Testability ranking',
      'Hypothesis-Driven Thinking - Killer question',
      'Hypothesis-Driven Thinking - Solution bias',
      'Risk Assessment and Strategic Planning - Impact x probability matrix',
      'Risk Assessment and Strategic Planning - Risk categorization',
      'Risk Assessment and Strategic Planning - Strategic planning frameworks',
      'Risk Assessment and Strategic Planning - Trade-off evaluation',
      'Risk Assessment and Strategic Planning - Scenario planning',
      'Quantitative Problem Solving - Market sizing',
      'Quantitative Problem Solving - Breakeven and payback period',
      'Quantitative Problem Solving - Profitability improvement levers',
      'Quantitative Problem Solving - Revenue and cost modeling',
      'Quantitative Problem Solving - Case math shortcuts',
    ],
    passFail: false,
    color: 'violet',
  },
  {
    id: 'communication',
    number: '4',
    name: 'Communication',
    description: 'How clearly and persuasively you communicate in professional contexts',
    assessmentType: 'MCQ + Written Task',
    totalQuestions: 15,
    skills: [
      'Professional Writing and Email - Pyramid Principle',
      'Professional Writing and Email - Tone and register',
      'Professional Writing and Email - Email structure',
      'Professional Writing and Email - Identifying poor communication',
      'Persuasion and Influence - Argument structure and strength',
      'Persuasion and Influence - Pyramid Principle in recommendations',
      'Persuasion and Influence - Persuasive framing',
      'Storytelling with Data - Insight headlines vs descriptive titles',
      'Storytelling with Data - Chart type selection',
      'Storytelling with Data - Framing data for executive audience',
      'Storytelling with Data - Misleading visualizations',
      'Business Writing Task - Business proposals',
      'Business Writing Task - Reports',
      'Business Writing Task - Executive summaries',
      'Business Writing Task - Persuasive pitches',
      'Negotiation and Professional Conflict - Principled negotiation',
      'Negotiation and Professional Conflict - BATNA',
      'Negotiation and Professional Conflict - Balancing outcomes and relationships',
      'Negotiation and Professional Conflict - Counter-proposal structure',
    ],
    passFail: false,
    color: 'amber',
  },
  {
    id: 'leadership',
    number: '5',
    name: 'Leadership',
    description:
      'How you respond to workplace situations requiring judgment, ethics, and leadership',
    assessmentType: 'Situational Judgment Test',
    totalQuestions: 20,
    skills: [
      'Team Leadership and Collaboration - Delegation',
      'Team Leadership and Collaboration - Managing underperformance',
      'Team Leadership and Collaboration - Psychological safety',
      'Team Leadership and Collaboration - Cross-functional collaboration',
      'Team Leadership and Collaboration - Recognition and motivation',
      'Conflict Resolution - Timing and medium of conflict',
      'Conflict Resolution - SBI feedback model',
      'Conflict Resolution - De-escalation',
      'Conflict Resolution - Impartiality in team disputes',
      'Conflict Resolution - Fairness vs decisiveness',
      'Decision-Making and Accountability - Deciding under incomplete information',
      'Decision-Making and Accountability - Escalation vs ownership',
      'Decision-Making and Accountability - Decision documentation',
      'Decision-Making and Accountability - Ownership of poor outcomes',
      'Decision-Making and Accountability - Speed vs thoroughness trade-off',
      'Emotional Intelligence and Empathy - Recognizing emotional signals',
      'Emotional Intelligence and Empathy - Self-regulation under pressure',
      'Emotional Intelligence and Empathy - Empathetic response within professional boundaries',
      'Emotional Intelligence and Empathy - Adjusting communication style by context',
      'Emotional Intelligence and Empathy - Reading interpersonal dynamics',
      'Ethical Judgment - Conflict of interest',
      'Ethical Judgment - Selective disclosure',
      'Ethical Judgment - Pressure to compromise standards',
      'Ethical Judgment - Governance shortcuts',
      'Ethical Judgment - Whistleblowing judgment',
    ],
    passFail: false,
    color: 'rose',
  },
  {
    id: 'digital-business',
    number: '6',
    name: 'Digital Business',
    description:
      'How aware and capable you are with data, AI, and digital tools in business contexts',
    assessmentType: 'Applied MCQ',
    totalQuestions: 15,
    skills: [
      'Data Literacy - KPI selection',
      'Data Literacy - Dashboard reading',
      'Data Literacy - Data quality issues',
      'Data Literacy - Cohort analysis',
      'Data Literacy - Correlation vs causation',
      'GenAI and LLM Business Applications - Selecting the right GenAI tool',
      'GenAI and LLM Business Applications - Hallucination detection',
      'GenAI and LLM Business Applications - Prompt engineering',
      'GenAI and LLM Business Applications - AI governance',
      'GenAI and LLM Business Applications - Human judgment vs AI assistance',
      'AI Awareness and Data Analytics - Precision vs recall',
      'AI Awareness and Data Analytics - AI bias',
      'AI Awareness and Data Analytics - Build vs buy vs partner',
      'AI Awareness and Data Analytics - ETL',
      'AI Awareness and Data Analytics - AI project failure modes',
      'Digital Marketing Fundamentals - SEO vs SEM',
      'Digital Marketing Fundamentals - ROAS',
      'Digital Marketing Fundamentals - Attribution models',
      'Digital Marketing Fundamentals - Conversion rate optimization',
      'Digital Marketing Fundamentals - Customer acquisition cost',
      'Automation and No-Code Tools - RPA suitability',
      'Automation and No-Code Tools - No-code tools',
      'Automation and No-Code Tools - AI-powered vs rule-based automation',
      'Automation and No-Code Tools - Automation ROI',
      'Automation and No-Code Tools - Limits of automation',
      'Cloud and Digital Infrastructure - SaaS vs PaaS vs IaaS',
      'Cloud and Digital Infrastructure - Capex vs opex',
      'Cloud and Digital Infrastructure - Data sovereignty and DPDP Act',
      'Cloud and Digital Infrastructure - Cloud-native vs cloud-ready',
      'Cloud and Digital Infrastructure - Multi-cloud strategy',
      'Business Tools Proficiency - CRM platforms',
      'Business Tools Proficiency - HRIS systems',
      'Business Tools Proficiency - BI tools',
      'Business Tools Proficiency - Project management tools',
      'Business Tools Proficiency - iPaaS and integration tools',
    ],
    passFail: false,
    color: 'cyan',
  },
  {
    id: 'workspace-psychology',
    number: 'G',
    name: 'Workspace Psychology GATE',
    description: 'Who you are in a workplace — behavioural profile',
    assessmentType: 'Ipsative Psychometric',
    totalQuestions: 20,
    skills: [
      'Stress resilience',
      'Grit & initiative',
      'Professionalism',
      'Cultural adaptability',
      'Accountability',
    ],
    passFail: true,
    color: 'orange',
  },
];

export const DOMAIN_MAP = Object.fromEntries(
  DOMAINS.map((d) => [d.id, d])
) as Record<DomainId, Domain>;

/** Assessment types that require a case/scenario context block */
export const CASE_BASED_TYPES = new Set([
  'Case-based MCQ',
  'Case Simulation + MCQ',
  'Situational Judgment Test',
]);

/** Assessment types that do NOT have a single "correct" answer */
export const NO_CORRECT_ANSWER_TYPES = new Set(['Ipsative Psychometric']);
